# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
# Forge for 1.16.5 is version 36
loaderVersion="[36,)"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/ChaosDogG/FrivyCat-Inc-Mod/issues"

# If the mods defined in this file should show as separate resource packs
showAsResourcePack=false
license = "GPL-3.0-or-later"

[[mods]]
    modId="frivycat"
    version="${file.jarVersion}"
    displayName="FrivyCat Inc. Mod"
    logoFile="pack.png"
    credits="I'd like to thank NetherNoah, who is helping me develop this mod!"
    authors="ChaosDog, NetherNoah777"
    description="Based on the §aFrivyCat Inc.§r Datapack" # Added color codes cause why not

[[dependencies.frivycat]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.frivycat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
